[package]
name = "devhub-community"
version = "0.1.0"
authors = ["NEAR DevHub <neardevhub.org>"]
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bs58 = "0.5.1"
sha2 = "0.10.8"

[dependencies]
near-sdk.workspace = true
devhub_common.workspace = true
